'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto Visual Studio.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class javascript_global
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.javascript_global", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        '''  le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Errore Account. Server Occupato.
        '''</summary>
        Friend Shared ReadOnly Property add_account_error() As String
            Get
                Return ResourceManager.GetString("add_account_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Account Aggiunto Con Successo.
        '''</summary>
        Friend Shared ReadOnly Property add_account_ok() As String
            Get
                Return ResourceManager.GetString("add_account_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Salvataggio Annullato.
        '''</summary>
        Friend Shared ReadOnly Property annulla_impianto() As String
            Get
                Return ResourceManager.GetString("annulla_impianto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Annulla.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Aggiungere un nuovo impianto?.
        '''</summary>
        Friend Shared ReadOnly Property confirm_add() As String
            Get
                Return ResourceManager.GetString("confirm_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Aggiungere un nuovo Utuilizzatore?.
        '''</summary>
        Friend Shared ReadOnly Property confirm_add_user() As String
            Get
                Return ResourceManager.GetString("confirm_add_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Modificare l\&apos; Utilizzatore?.
        '''</summary>
        Friend Shared ReadOnly Property confirm_modify_user() As String
            Get
                Return ResourceManager.GetString("confirm_modify_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Data/Ora Errata.
        '''</summary>
        Friend Shared ReadOnly Property date_time_wrong() As String
            Get
                Return ResourceManager.GetString("date_time_wrong", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Eliminare il controller.
        '''</summary>
        Friend Shared ReadOnly Property delete_controller() As String
            Get
                Return ResourceManager.GetString("delete_controller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Eliminare i l\&apos;impianto.
        '''</summary>
        Friend Shared ReadOnly Property delete_plant() As String
            Get
                Return ResourceManager.GetString("delete_plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Eliminare i l\&apos;Utilizzatore.
        '''</summary>
        Friend Shared ReadOnly Property delete_user() As String
            Get
                Return ResourceManager.GetString("delete_user", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Errore Eliminazione Impianto. Server Occupato.
        '''</summary>
        Friend Shared ReadOnly Property elimina_impianto_error() As String
            Get
                Return ResourceManager.GetString("elimina_impianto_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Eliminazione Impianto Avvenuta con Seccesso.
        '''</summary>
        Friend Shared ReadOnly Property elimina_impianto_ok() As String
            Get
                Return ResourceManager.GetString("elimina_impianto_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Errore Eliminazione Utilizzatore. Server Occupato.
        '''</summary>
        Friend Shared ReadOnly Property elimina_user_error() As String
            Get
                Return ResourceManager.GetString("elimina_user_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Eliminazione Utilizzatore Avvenuta con Seccesso.
        '''</summary>
        Friend Shared ReadOnly Property elimina_user_ok() As String
            Get
                Return ResourceManager.GetString("elimina_user_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserisci una mail valida.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Grafico Log.
        '''</summary>
        Friend Shared ReadOnly Property graph_log() As String
            Get
                Return ResourceManager.GetString("graph_log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserisci una descrizione dell\&apos;impianto.
        '''</summary>
        Friend Shared ReadOnly Property impianto_descrizione_place() As String
            Get
                Return ResourceManager.GetString("impianto_descrizione_place", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Impianto Duplicato.
        '''</summary>
        Friend Shared ReadOnly Property impianto_duplicato() As String
            Get
                Return ResourceManager.GetString("impianto_duplicato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a L\&apos;intervallo del grafico Log non puo superare 30 Giorni.
        '''</summary>
        Friend Shared ReadOnly Property intervallo_log() As String
            Get
                Return ResourceManager.GetString("intervallo_log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Indirizzo mail errato.
        '''</summary>
        Friend Shared ReadOnly Property invalid_mail_format() As String
            Get
                Return ResourceManager.GetString("invalid_mail_format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Errore modifica account. Server Occupato.
        '''</summary>
        Friend Shared ReadOnly Property modify_account_error() As String
            Get
                Return ResourceManager.GetString("modify_account_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Modifica Account Avvenuta con Successo.
        '''</summary>
        Friend Shared ReadOnly Property modify_account_ok() As String
            Get
                Return ResourceManager.GetString("modify_account_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sei sicuro di voler Modificare i Parametri dell\&apos;impianto?.
        '''</summary>
        Friend Shared ReadOnly Property modify_plant() As String
            Get
                Return ResourceManager.GetString("modify_plant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Modifica paramteri dell\&apos;impianto Annullata.. Impianto Occupato....
        '''</summary>
        Friend Shared ReadOnly Property modify_plant_error() As String
            Get
                Return ResourceManager.GetString("modify_plant_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Parametri dell\&apos;impianto modificati con successo...
        '''</summary>
        Friend Shared ReadOnly Property modify_plant_ok() As String
            Get
                Return ResourceManager.GetString("modify_plant_ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Valore Numerico.
        '''</summary>
        Friend Shared ReadOnly Property numeric_digit() As String
            Get
                Return ResourceManager.GetString("numeric_digit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a OK.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserisci Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a La password deve contenere almeno 6 caratteri.
        '''</summary>
        Friend Shared ReadOnly Property password_6() As String
            Get
                Return ResourceManager.GetString("password_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a La nuova password deve contenere almeno 6 caratteri.
        '''</summary>
        Friend Shared ReadOnly Property password_6_new() As String
            Get
                Return ResourceManager.GetString("password_6_new", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ripeti correttamente la password.
        '''</summary>
        Friend Shared ReadOnly Property password_uguale() As String
            Get
                Return ResourceManager.GetString("password_uguale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Accetta le condizioni.
        '''</summary>
        Friend Shared ReadOnly Property policy() As String
            Get
                Return ResourceManager.GetString("policy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Intervallo.
        '''</summary>
        Friend Shared ReadOnly Property range() As String
            Get
                Return ResourceManager.GetString("range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Obbligatorio.
        '''</summary>
        Friend Shared ReadOnly Property required() As String
            Get
                Return ResourceManager.GetString("required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Modifica paramteri dell\&apos;impianto Annullata.. Server Occupato....
        '''</summary>
        Friend Shared ReadOnly Property server_error() As String
            Get
                Return ResourceManager.GetString("server_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Inserisci una Username.
        '''</summary>
        Friend Shared ReadOnly Property username() As String
            Get
                Return ResourceManager.GetString("username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a La Username deve contenere almeno 6 caratteri.
        '''</summary>
        Friend Shared ReadOnly Property username_6() As String
            Get
                Return ResourceManager.GetString("username_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Utente non Abilitato alla modifica dei Parametri dell\&apos;Impianto.
        '''</summary>
        Friend Shared ReadOnly Property user_setpoint_disable() As String
            Get
                Return ResourceManager.GetString("user_setpoint_disable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Utilizzatore Duplicato.
        '''</summary>
        Friend Shared ReadOnly Property utilizzatore_duplicato() As String
            Get
                Return ResourceManager.GetString("utilizzatore_duplicato", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Vecchia password errata.
        '''</summary>
        Friend Shared ReadOnly Property wrong_old_password() As String
            Get
                Return ResourceManager.GetString("wrong_old_password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Errore impostazione.
        '''</summary>
        Friend Shared ReadOnly Property wrong_settings() As String
            Get
                Return ResourceManager.GetString("wrong_settings", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
