'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto Visual Studio.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ld_global
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.ld_global", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        '''  le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Acid:.
        '''</summary>
        Friend Shared ReadOnly Property Acido_() As String
            Get
                Return ResourceManager.GetString("Acido_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Alert.
        '''</summary>
        Friend Shared ReadOnly Property Alert() As String
            Get
                Return ResourceManager.GetString("Alert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Read Alarm.
        '''</summary>
        Friend Shared ReadOnly Property AllRead() As String
            Get
                Return ResourceManager.GetString("AllRead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Analog Input.
        '''</summary>
        Friend Shared ReadOnly Property Analog_Input() As String
            Get
                Return ResourceManager.GetString("Analog_Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Assistance Renewal.
        '''</summary>
        Friend Shared ReadOnly Property Assistenza() As String
            Get
                Return ResourceManager.GetString("Assistenza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Auto setpoint.
        '''</summary>
        Friend Shared ReadOnly Property Autosetpoint() As String
            Get
                Return ResourceManager.GetString("Autosetpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Batch Tank Empty.
        '''</summary>
        Friend Shared ReadOnly Property Batch_Tank_Empty() As String
            Get
                Return ResourceManager.GetString("Batch_Tank_Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Calibrazione.
        '''</summary>
        Friend Shared ReadOnly Property calibartion() As String
            Get
                Return ResourceManager.GetString("calibartion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Calibrazione.
        '''</summary>
        Friend Shared ReadOnly Property calibration() As String
            Get
                Return ResourceManager.GetString("calibration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Calibrazione.
        '''</summary>
        Friend Shared ReadOnly Property calibrationB() As String
            Get
                Return ResourceManager.GetString("calibrationB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Canale.
        '''</summary>
        Friend Shared ReadOnly Property Channels() As String
            Get
                Return ResourceManager.GetString("Channels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Chlorite:.
        '''</summary>
        Friend Shared ReadOnly Property Chlorite_() As String
            Get
                Return ResourceManager.GetString("Chlorite_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Cicli.
        '''</summary>
        Friend Shared ReadOnly Property Cicli() As String
            Get
                Return ResourceManager.GetString("Cicli", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Circulation.
        '''</summary>
        Friend Shared ReadOnly Property Circulation() As String
            Get
                Return ResourceManager.GetString("Circulation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a ClO2 limit.
        '''</summary>
        Friend Shared ReadOnly Property CLO2_limit() As String
            Get
                Return ResourceManager.GetString("CLO2_limit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Contact SEFL Acid.
        '''</summary>
        Friend Shared ReadOnly Property Contact_SEFL_Acid() As String
            Get
                Return ResourceManager.GetString("Contact_SEFL_Acid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Contact SEFL Chlorite.
        '''</summary>
        Friend Shared ReadOnly Property Contact_SEFL_Chlorite() As String
            Get
                Return ResourceManager.GetString("Contact_SEFL_Chlorite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Dosing Alarm.
        '''</summary>
        Friend Shared ReadOnly Property dosing_alarm() As String
            Get
                Return ResourceManager.GetString("dosing_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Filter.
        '''</summary>
        Friend Shared ReadOnly Property Filtro() As String
            Get
                Return ResourceManager.GetString("Filtro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flusso.
        '''</summary>
        Friend Shared ReadOnly Property flow() As String
            Get
                Return ResourceManager.GetString("flow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow Alarm.
        '''</summary>
        Friend Shared ReadOnly Property Flowall() As String
            Get
                Return ResourceManager.GetString("Flowall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flusso.
        '''</summary>
        Friend Shared ReadOnly Property flowB() As String
            Get
                Return ResourceManager.GetString("flowB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow Control Acid.
        '''</summary>
        Friend Shared ReadOnly Property Flow_Control_Acid() As String
            Get
                Return ResourceManager.GetString("Flow_Control_Acid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow Control Cloro.
        '''</summary>
        Friend Shared ReadOnly Property Flow_Control_Cloro() As String
            Get
                Return ResourceManager.GetString("Flow_Control_Cloro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow Control Water.
        '''</summary>
        Friend Shared ReadOnly Property Flow_Control_Water() As String
            Get
                Return ResourceManager.GetString("Flow_Control_Water", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow meter:.
        '''</summary>
        Friend Shared ReadOnly Property Flow_M() As String
            Get
                Return ResourceManager.GetString("Flow_M", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Flow Water Dlution.
        '''</summary>
        Friend Shared ReadOnly Property Flow_Water_Dlution() As String
            Get
                Return ResourceManager.GetString("Flow_Water_Dlution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a High Range Alarm.
        '''</summary>
        Friend Shared ReadOnly Property high_range_alarm() As String
            Get
                Return ResourceManager.GetString("high_range_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Ingressi.
        '''</summary>
        Friend Shared ReadOnly Property ingressi() As String
            Get
                Return ResourceManager.GetString("ingressi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a International.
        '''</summary>
        Friend Shared ReadOnly Property international() As String
            Get
                Return ResourceManager.GetString("international", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Time.
        '''</summary>
        Friend Shared ReadOnly Property internationalB() As String
            Get
                Return ResourceManager.GetString("internationalB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Channels.
        '''</summary>
        Friend Shared ReadOnly Property ld_ma_channel() As String
            Get
                Return ResourceManager.GetString("ld_ma_channel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date Time.
        '''</summary>
        Friend Shared ReadOnly Property ld_ma_date() As String
            Get
                Return ResourceManager.GetString("ld_ma_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level.
        '''</summary>
        Friend Shared ReadOnly Property level() As String
            Get
                Return ResourceManager.GetString("level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Acid.
        '''</summary>
        Friend Shared ReadOnly Property Level_acid() As String
            Get
                Return ResourceManager.GetString("Level_acid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Chlorite.
        '''</summary>
        Friend Shared ReadOnly Property Level_cloro() As String
            Get
                Return ResourceManager.GetString("Level_cloro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Livello HCl.
        '''</summary>
        Friend Shared ReadOnly Property Level_HCL() As String
            Get
                Return ResourceManager.GetString("Level_HCL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Livello NaClO2.
        '''</summary>
        Friend Shared ReadOnly Property Level_NACLO2() As String
            Get
                Return ResourceManager.GetString("Level_NACLO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Serbatoio Stoccaggio Pieno.
        '''</summary>
        Friend Shared ReadOnly Property Level_STORAGE() As String
            Get
                Return ResourceManager.GetString("Level_STORAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Water.
        '''</summary>
        Friend Shared ReadOnly Property Level_Water() As String
            Get
                Return ResourceManager.GetString("Level_Water", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Livello.
        '''</summary>
        Friend Shared ReadOnly Property livello_ldma() As String
            Get
                Return ResourceManager.GetString("livello_ldma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Log.
        '''</summary>
        Friend Shared ReadOnly Property Log() As String
            Get
                Return ResourceManager.GetString("Log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Log Setup.
        '''</summary>
        Friend Shared ReadOnly Property log_setup() As String
            Get
                Return ResourceManager.GetString("log_setup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Log Setup.
        '''</summary>
        Friend Shared ReadOnly Property log_setupB() As String
            Get
                Return ResourceManager.GetString("log_setupB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Low Range Alarm.
        '''</summary>
        Friend Shared ReadOnly Property low_range_alarm() As String
            Get
                Return ResourceManager.GetString("low_range_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Manual.
        '''</summary>
        Friend Shared ReadOnly Property manual() As String
            Get
                Return ResourceManager.GetString("manual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a maintenance.
        '''</summary>
        Friend Shared ReadOnly Property Manutenzione() As String
            Get
                Return ResourceManager.GetString("Manutenzione", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a max mA.
        '''</summary>
        Friend Shared ReadOnly Property max_ma() As String
            Get
                Return ResourceManager.GetString("max_ma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Max Temperature.
        '''</summary>
        Friend Shared ReadOnly Property max_temperature() As String
            Get
                Return ResourceManager.GetString("max_temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a mA Outupt.
        '''</summary>
        Friend Shared ReadOnly Property ma_output() As String
            Get
                Return ResourceManager.GetString("ma_output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Messaggi.
        '''</summary>
        Friend Shared ReadOnly Property message() As String
            Get
                Return ResourceManager.GetString("message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Contatore.
        '''</summary>
        Friend Shared ReadOnly Property Meter() As String
            Get
                Return ResourceManager.GetString("Meter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a min mA.
        '''</summary>
        Friend Shared ReadOnly Property min_ma() As String
            Get
                Return ResourceManager.GetString("min_ma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Min/max High.
        '''</summary>
        Friend Shared ReadOnly Property min_max_high() As String
            Get
                Return ResourceManager.GetString("min_max_high", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Min/max Low.
        '''</summary>
        Friend Shared ReadOnly Property min_max_low() As String
            Get
                Return ResourceManager.GetString("min_max_low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Min Temperature.
        '''</summary>
        Friend Shared ReadOnly Property min_temperature() As String
            Get
                Return ResourceManager.GetString("min_temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Out Of Range Alarm.
        '''</summary>
        Friend Shared ReadOnly Property out_of_range_alarm() As String
            Get
                Return ResourceManager.GetString("out_of_range_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Overflow.
        '''</summary>
        Friend Shared ReadOnly Property Overflow() As String
            Get
                Return ResourceManager.GetString("Overflow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Parameters.
        '''</summary>
        Friend Shared ReadOnly Property parameters() As String
            Get
                Return ResourceManager.GetString("parameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Parametri.
        '''</summary>
        Friend Shared ReadOnly Property parametersB() As String
            Get
                Return ResourceManager.GetString("parametersB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pre Dilution Water.
        '''</summary>
        Friend Shared ReadOnly Property Pre_Dilution_Water() As String
            Get
                Return ResourceManager.GetString("Pre_Dilution_Water", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Probe Failure.
        '''</summary>
        Friend Shared ReadOnly Property probe_failure() As String
            Get
                Return ResourceManager.GetString("probe_failure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Pulse.
        '''</summary>
        Friend Shared ReadOnly Property pulse() As String
            Get
                Return ResourceManager.GetString("pulse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Range Alarm.
        '''</summary>
        Friend Shared ReadOnly Property range_alarm() As String
            Get
                Return ResourceManager.GetString("range_alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Reactor Leakage.
        '''</summary>
        Friend Shared ReadOnly Property Reactor_Leakage() As String
            Get
                Return ResourceManager.GetString("Reactor_Leakage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Relay.
        '''</summary>
        Friend Shared ReadOnly Property relay() As String
            Get
                Return ResourceManager.GetString("relay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Reset.
        '''</summary>
        Friend Shared ReadOnly Property ResetA() As String
            Get
                Return ResourceManager.GetString("ResetA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Salva e carica i dati.
        '''</summary>
        Friend Shared ReadOnly Property salva_carica_dati() As String
            Get
                Return ResourceManager.GetString("salva_carica_dati", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Self Clean.
        '''</summary>
        Friend Shared ReadOnly Property Self() As String
            Get
                Return ResourceManager.GetString("Self", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Service And Calibration Required.
        '''</summary>
        Friend Shared ReadOnly Property Service_And_Calibration_Required() As String
            Get
                Return ResourceManager.GetString("Service_And_Calibration_Required", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a SetPoint.
        '''</summary>
        Friend Shared ReadOnly Property setpoint() As String
            Get
                Return ResourceManager.GetString("setpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Set Points.
        '''</summary>
        Friend Shared ReadOnly Property setpointB() As String
            Get
                Return ResourceManager.GetString("setpointB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Cal.Sonda.
        '''</summary>
        Friend Shared ReadOnly Property Sonde() As String
            Get
                Return ResourceManager.GetString("Sonde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Stand-By.
        '''</summary>
        Friend Shared ReadOnly Property standby() As String
            Get
                Return ResourceManager.GetString("standby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sistema.
        '''</summary>
        Friend Shared ReadOnly Property System() As String
            Get
                Return ResourceManager.GetString("System", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Massimo Tempo Raggiunto.
        '''</summary>
        Friend Shared ReadOnly Property Tempo_Massimo() As String
            Get
                Return ResourceManager.GetString("Tempo_Massimo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tempo (min).
        '''</summary>
        Friend Shared ReadOnly Property time() As String
            Get
                Return ResourceManager.GetString("time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Timeout.
        '''</summary>
        Friend Shared ReadOnly Property Timeout() As String
            Get
                Return ResourceManager.GetString("Timeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Consumo Giorno.
        '''</summary>
        Friend Shared ReadOnly Property totalizzatore_giornaliero_ldma() As String
            Get
                Return ResourceManager.GetString("totalizzatore_giornaliero_ldma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Consumo Tot..
        '''</summary>
        Friend Shared ReadOnly Property totalizzatore_ldma() As String
            Get
                Return ResourceManager.GetString("totalizzatore_ldma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Uscite.
        '''</summary>
        Friend Shared ReadOnly Property uscite() As String
            Get
                Return ResourceManager.GetString("uscite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Calibrazioni.
        '''</summary>
        Friend Shared ReadOnly Property val_calibration() As String
            Get
                Return ResourceManager.GetString("val_calibration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Canale.
        '''</summary>
        Friend Shared ReadOnly Property val_canale() As String
            Get
                Return ResourceManager.GetString("val_canale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Mode.
        '''</summary>
        Friend Shared ReadOnly Property val_Mode() As String
            Get
                Return ResourceManager.GetString("val_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a mV Sonda.
        '''</summary>
        Friend Shared ReadOnly Property val_mvprobe() As String
            Get
                Return ResourceManager.GetString("val_mvprobe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a OFF.
        '''</summary>
        Friend Shared ReadOnly Property val_OFF() As String
            Get
                Return ResourceManager.GetString("val_OFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a ON.
        '''</summary>
        Friend Shared ReadOnly Property val_ON() As String
            Get
                Return ResourceManager.GetString("val_ON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a sec.
        '''</summary>
        Friend Shared ReadOnly Property val_sec() As String
            Get
                Return ResourceManager.GetString("val_sec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Nuovo Valore.
        '''</summary>
        Friend Shared ReadOnly Property val_valuenew() As String
            Get
                Return ResourceManager.GetString("val_valuenew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Valore Sonda.
        '''</summary>
        Friend Shared ReadOnly Property val_valueprobe() As String
            Get
                Return ResourceManager.GetString("val_valueprobe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Wating for Restart.
        '''</summary>
        Friend Shared ReadOnly Property waiting() As String
            Get
                Return ResourceManager.GetString("waiting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Water Meter:.
        '''</summary>
        Friend Shared ReadOnly Property WMeter() As String
            Get
                Return ResourceManager.GetString("WMeter", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
