'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto Visual Studio.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class main_master_global
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.main_master_global", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        '''  le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Aggiungi.
        '''</summary>
        Friend Shared ReadOnly Property aggiungi() As String
            Get
                Return ResourceManager.GetString("aggiungi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Aggiungi Impianto.
        '''</summary>
        Friend Shared ReadOnly Property aggiungi_impianto() As String
            Get
                Return ResourceManager.GetString("aggiungi_impianto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Comunicazioni.
        '''</summary>
        Friend Shared ReadOnly Property communication() As String
            Get
                Return ResourceManager.GetString("communication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Dashboard.
        '''</summary>
        Friend Shared ReadOnly Property dashboard() As String
            Get
                Return ResourceManager.GetString("dashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Documentation.
        '''</summary>
        Friend Shared ReadOnly Property documentation() As String
            Get
                Return ResourceManager.GetString("documentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Modifica.
        '''</summary>
        Friend Shared ReadOnly Property edit() As String
            Get
                Return ResourceManager.GetString("edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Elimina.
        '''</summary>
        Friend Shared ReadOnly Property elimina() As String
            Get
                Return ResourceManager.GetString("elimina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Elimina Controller.
        '''</summary>
        Friend Shared ReadOnly Property eliminaController() As String
            Get
                Return ResourceManager.GetString("eliminaController", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Getting Started.
        '''</summary>
        Friend Shared ReadOnly Property gettingDashboard() As String
            Get
                Return ResourceManager.GetString("gettingDashboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Impianti.
        '''</summary>
        Friend Shared ReadOnly Property impianti() As String
            Get
                Return ResourceManager.GetString("impianti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Latest Log.
        '''</summary>
        Friend Shared ReadOnly Property latestLog() As String
            Get
                Return ResourceManager.GetString("latestLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Modifica.
        '''</summary>
        Friend Shared ReadOnly Property modifica() As String
            Get
                Return ResourceManager.GetString("modifica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Nessun Impianto.
        '''</summary>
        Friend Shared ReadOnly Property nessun_impianto() As String
            Get
                Return ResourceManager.GetString("nessun_impianto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Impostazioni.
        '''</summary>
        Friend Shared ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Esci.
        '''</summary>
        Friend Shared ReadOnly Property signout() As String
            Get
                Return ResourceManager.GetString("signout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Upload File.
        '''</summary>
        Friend Shared ReadOnly Property uploadFile() As String
            Get
                Return ResourceManager.GetString("uploadFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a USB Log Manager.
        '''</summary>
        Friend Shared ReadOnly Property usbManager() As String
            Get
                Return ResourceManager.GetString("usbManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Utilizzatore.
        '''</summary>
        Friend Shared ReadOnly Property utilizzatore() As String
            Get
                Return ResourceManager.GetString("utilizzatore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Benvenuto.
        '''</summary>
        Friend Shared ReadOnly Property welcome() As String
            Get
                Return ResourceManager.GetString("welcome", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
