'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto Visual Studio.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class tower_global
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.tower_global", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        '''  le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Biocide.
        '''</summary>
        Friend Shared ReadOnly Property biocide() As String
            Get
                Return ResourceManager.GetString("biocide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bleed.
        '''</summary>
        Friend Shared ReadOnly Property bleed() As String
            Get
                Return ResourceManager.GetString("bleed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bleed Timeout.
        '''</summary>
        Friend Shared ReadOnly Property bleed_timeout() As String
            Get
                Return ResourceManager.GetString("bleed_timeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Conductivity.
        '''</summary>
        Friend Shared ReadOnly Property conductivity() As String
            Get
                Return ResourceManager.GetString("conductivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Date.
        '''</summary>
        Friend Shared ReadOnly Property data() As String
            Get
                Return ResourceManager.GetString("data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Digital.
        '''</summary>
        Friend Shared ReadOnly Property digital() As String
            Get
                Return ResourceManager.GetString("digital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a High.
        '''</summary>
        Friend Shared ReadOnly Property high() As String
            Get
                Return ResourceManager.GetString("high", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a High Conductivity.
        '''</summary>
        Friend Shared ReadOnly Property high_conductivity() As String
            Get
                Return ResourceManager.GetString("high_conductivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a InhibitorDig.
        '''</summary>
        Friend Shared ReadOnly Property inhibitordig() As String
            Get
                Return ResourceManager.GetString("inhibitordig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a InhibitorProp.
        '''</summary>
        Friend Shared ReadOnly Property inhibitorprop() As String
            Get
                Return ResourceManager.GetString("inhibitorprop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level.
        '''</summary>
        Friend Shared ReadOnly Property level() As String
            Get
                Return ResourceManager.GetString("level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Biocide.
        '''</summary>
        Friend Shared ReadOnly Property level_biocide() As String
            Get
                Return ResourceManager.GetString("level_biocide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Inhibitor.
        '''</summary>
        Friend Shared ReadOnly Property level_inhibitor() As String
            Get
                Return ResourceManager.GetString("level_inhibitor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Level Prebiocide.
        '''</summary>
        Friend Shared ReadOnly Property level_prebiocide() As String
            Get
                Return ResourceManager.GetString("level_prebiocide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a LockOut.
        '''</summary>
        Friend Shared ReadOnly Property lockout() As String
            Get
                Return ResourceManager.GetString("lockout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Low.
        '''</summary>
        Friend Shared ReadOnly Property low() As String
            Get
                Return ResourceManager.GetString("low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Low Conductivity.
        '''</summary>
        Friend Shared ReadOnly Property low_conductivity() As String
            Get
                Return ResourceManager.GetString("low_conductivity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a PreBiocide.
        '''</summary>
        Friend Shared ReadOnly Property prebiocide() As String
            Get
                Return ResourceManager.GetString("prebiocide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a PreBleed.
        '''</summary>
        Friend Shared ReadOnly Property prebleed() As String
            Get
                Return ResourceManager.GetString("prebleed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Proportional.
        '''</summary>
        Friend Shared ReadOnly Property Proportional() As String
            Get
                Return ResourceManager.GetString("Proportional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Status Biocide Day.
        '''</summary>
        Friend Shared ReadOnly Property status_biocide_day() As String
            Get
                Return ResourceManager.GetString("status_biocide_day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Status Biocide Week.
        '''</summary>
        Friend Shared ReadOnly Property status_biocide_week() As String
            Get
                Return ResourceManager.GetString("status_biocide_week", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Water Meter Bleed.
        '''</summary>
        Friend Shared ReadOnly Property water_meter_bleed() As String
            Get
                Return ResourceManager.GetString("water_meter_bleed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Water Meter Difference.
        '''</summary>
        Friend Shared ReadOnly Property water_meter_difference() As String
            Get
                Return ResourceManager.GetString("water_meter_difference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Water Meter Input.
        '''</summary>
        Friend Shared ReadOnly Property water_meter_input() As String
            Get
                Return ResourceManager.GetString("water_meter_input", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
